### ISSUE TITLE
can't find file 'secure_random'

### ISSUE THREAD

**Issue by willysunny** [denysvitali/megadecrypter#2]
as title suggested

When I tried to build the project, I encountered with this error message

root@ubuntu:~/megadecrypter# crystal build --release src/megadecrypter.cr
Error in src/megadecrypter.cr:4: while requiring "secure_random": can't find file 'secure_random' relative to '/root/megadecrypter/src'

require "secure_random"
^

**Comment by denysvitali** [comment]
Fixed.  
`SecureRandom` was renamed to `Random::Secure` in 0.24.x.  
  
Apparently I wasn't using random either, it might have been a unused require.  
Can you please test (`git pull` again) and report back if it works? I've just tried on my computer w/ `Crystal 0.24.1 (2017-12-20)` and it works after my 45dc3f9 commit :rocket:

**Comment by rdp** [comment]
for followers it's `require "random/secure"` now FWIW
